### ISSUE TITLE
Update Time Parsing

### ISSUE THREAD

**Issue by TheTedder** [Ekelbatzen/LiveSplit.Remote.Android#4]
I'm currently working on an update to the LiveSplit server that slightly changes the way times and deltas are formatted in communications between apps, and during testing I noticed that the proposed change breaks this app. The new time format is https://learn.microsoft.com/en-us/dotnet/standard/base-types/standard-timespan-format-strings#the-constant-c-format-specifier. The changes to the LiveSplit server have already been merged into master on that repo but I wanted to contact you and give you a chance to update this app before we release a new LiveSplit version with a breaking change. Let me know if you have any questions and feel free to hop in the [LiveSplit discord](https://discord.gg/N6wv8pW) if you want to work more closely with us regarding the changes.

**Comment by robins42** [comment]
Thank you for the heads-up, I would have missed this entirely and be notified by angry users. I will try to test and adapt the app for this.

**Comment by robins42** [comment]
Rollout of the new version 0.5.0 of the app has started, which supports the old and the new server formats.
